var bankName = "SBI Bank";
console.log("Bank Name: " +bankName);
console.log(typeof bankName);
console.log("-----------------------");
var marks = "90%";
console.log("Marks: " +marks);
console.log(typeof marks);
console.log("-----------------------");
var isWorking = true;
console.log("Is Working: "+isWorking);
console.log(typeof isWorking);
console.log("-----------------------");
var totalCount = "Hundred and seven";
console.log("Total count: " +totalCount);
console.log(typeof totalCount);
console.log("-----------------------");
var totalCount = 107;
console.log("Total count: " +totalCount);
console.log(typeof totalCount);