console.log(``);
const fruitsSeasonal = ["Banana", "Orange", "Apple", "Mango","WaterMelon"];
console.log(`Given array is : "${fruitsSeasonal}"`);
console.log(`\n`);
console.log(`1) Log First and last element on the console.`);
let firstElement = fruitsSeasonal [0];
let lastElement = fruitsSeasonal [fruitsSeasonal.length-1];
console.log(`First element in the array is "${firstElement}" and last element is "${lastElement}".`);
console.log(`------------------------------------------------------------------------------------------------`);
console.log(`2) Add Papaya before Banana.`);
console.log(` Before adding Papaya: "${fruitsSeasonal}".`);
fruitsSeasonal.unshift("Papaya");
console.log(` After adding Papaya: "${fruitsSeasonal}".`);
console.log(`------------------------------------------------------------------------------------------------`);
console.log(`3) Remove Mango from Array.`);
console.log(` Before removing Mango: "${fruitsSeasonal}".`);
fruitsSeasonal.splice(4,1);
console.log(` After removing Mango: "${fruitsSeasonal}".`);
console.log(`------------------------------------------------------------------------------------------------`);
console.log(`4) Add Pineapple at the last index.`);
console.log(` Before adding Pineapple: "${fruitsSeasonal}".`);
fruitsSeasonal.push("Pineapple");
console.log(` After adding Pineapple: "${fruitsSeasonal}".`);
console.log(`------------------------------------------------------------------------------------------------`);
console.log(`5) Insert "Dragon Fruit" before Pineapple.`);
console.log(` Before adding Dragon Fruit: "${fruitsSeasonal}".`);
fruitsSeasonal.splice(fruitsSeasonal.length-1,0,"Dragon Fruit");
console.log(` After adding Dragon Fruit : "${fruitsSeasonal}".`);
console.log(`------------------------------------------------------------------------------------------------`);
console.log(`6) Replace "Orange" with "Kiwi"`);
console.log(` Before replacing Orange with Kiwi: "${fruitsSeasonal}".`);
fruitsSeasonal.splice(2,1,"Kiwi");
console.log(` After replacing Orange with Kiwi: "${fruitsSeasonal}".`);
console.log(`------------------------------------------------------------------------------------------------`);
console.log(`7)Log the elements starting from index 1 to 4.`);
console.log(` Given array: "${fruitsSeasonal}".`);
fruitsSeasonal.splice(5);
fruitsSeasonal.shift();
console.log(`Elements from index 1 to 4 are:  "${fruitsSeasonal}".`);
console.log(`------------------------------------------------------------------------------------------------`);
console.log(`8) Only select last three elements using length property.`);
let newFruitsSeasonal = ["Banana", "Orange", "Apple", "Mango","WaterMelon"];
console.log(`Given array : "${newFruitsSeasonal}"`);
let lastThree = newFruitsSeasonal.slice(newFruitsSeasonal.length-3);
console.log(`Last three elements in the array is : "${lastThree}"`);